services:
  frontend:
    image: deanalemao/mern-employee-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    image: deanalemao/mern-employee-backend:latest
    expose:
      - "5001"
    depends_on:
      - mongo
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    expose: 
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
